---
title: "Summary statistics of PMLB datasets"
output:
  tufte::tufte_html: default
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs_sources/")
  })
twitterImg: imgs/summary-plotly.png
---

The plot below is created with [plotly](https://plotly.com/).
Each dot represents a dataset colored based on its associated task (classification vs. regression).
In log scale, the *x* and *y* axis shows the number of observations and features respectively.
Please click on the legend to hide/show the groups of datasets.
Click on each dot to access the dataset's [pandas-profiling](https://pandas-profiling.github.io/pandas-profiling/docs/master/rtd/) report.

```{r setup, include=FALSE}
library(plotly)
library(tidyverse)
library(purrr)
library(htmlwidgets)
library(htmltools)
library(jsonlite)
```

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=10}
sum_stats <- read_csv('https://raw.githubusercontent.com/EpistasisLab/penn-ml-benchmarks/PMLB2.0/datasets/all_summary_stats.csv')

ply_dat <- sum_stats %>% 
  add_count(problem_type) %>% 
  mutate(Task = paste0(problem_type, ' (', n, ')'),
         urls = paste0(
           'https://epistasislab.github.io/penn-ml-benchmarks/profile/',
           dataset,
           '.html')) 

ggp <- ply_dat %>% 
  ggplot(aes(x = `#instances`, y = `#features`, color = Task)) +
  geom_point() +
  ggthemes::theme_solarized() +
  theme(legend.title = element_blank(),
        legend.position = 'bottom',
        # panel.grid.major = element_line(colour = "grey50"),
        panel.background = element_rect(fill = '#FFFFF8'),
        plot.background = element_rect(fill = '#FFFFF8')) +
  scale_x_log10(name = 'Number of observations',
                ) +
  scale_y_log10(name = 'Number of features') +
  scale_color_brewer(palette = 'Dark2') +
  NULL
ply <- plotly_build(ggp)


class_dats <- sum_stats %>% 
  filter(problem_type == 'classification') %>% 
  pull(dataset)
fig_lay1 <- gsub(pattern = '<br \\/>Task: classification \\(164\\)', replacement = '', ply$x$data[[1]]$text) %>% 
  gsub(pattern = '#instances:\\s+', '', .) %>% 
  gsub(pattern = '<br \\/>#features:\\s+', ' observations<br />', .) %>% 
  paste0(' features')

ply$x$data[[1]]$text <- paste0('<b>', class_dats, '</b><br /><br />', fig_lay1)

reg_dats <- sum_stats %>% 
  filter(problem_type == 'regression') %>% 
  pull(dataset)
fig_lay2 <- gsub(pattern = '<br \\/>Task: regression \\(122\\)', replacement = '', ply$x$data[[2]]$text) %>% 
  gsub(pattern = '#instances:\\s+', '', .) %>% 
  gsub(pattern = '<br \\/>#features:\\s+', ' observations<br />', .) %>% 
  paste0(' features')

ply$x$data[[2]]$text <- paste0('<b>', reg_dats, '</b><br /><br />', fig_lay2)


ply$elementId <- "PlotlyGraph"

javascript <- HTML(paste("var myPlot = document.getElementById('", ply$elementId, "');
                           myPlot.on('plotly_click', function(data){
                           var urls = ", toJSON(split(ply_dat, ply_dat$Task)), ";
                           window.open(urls[data.points[0].data.name][data.points[0].pointNumber]['urls'],'_blank');
                           });", sep=''))  

ply <- prependContent(ply, onStaticRenderComplete(javascript))
ply
# saveWidget(widget=ply, file=file.path('test.html'), selfcontained = FALSE)
```

